### ISSUE TITLE
Need a checkbox

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/contao-frontend-editing#1]
We need a checkbox for the frontend which works likes the one in the backend.

**Comment by discordier** [comment]
I guess this is rather a bugfix than feature as the current checkboxes with two checkbox values (in the matter of MM active and inactive) are pretty useless.

**Comment by discordier** [comment]
The commits you made (81e9965, 38369b9, 0cc04ba) should rather end up in the checkbox attribute.
I added it as comment to MetaModels/attribute_checkbox#17.

What do you think?

**Comment by zonky2** [comment]
@richardhj can you check this and update or close this ticket

**Comment by richardhj** [comment]
Already done with MetaModels/attribute_checkbox@b65a6a5dd9e6faa3b45eaf53211780c16537970e in the checkbox repository. That's what @discordier stated in https://github.com/MetaModels/contao-frontend-editing/issues/1#issuecomment-268245016.
Too bad this ticket wasn't closed. Took me to long to cherry-pick the commits on my own and noticing it was already done afterwards.
