### ISSUE TITLE
Error URL-Attribut beim FE

### ISSUE THREAD

**Issue by Schmidty2** [MetaModels/contao-frontend-editing#10]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

PHP 5.6.30

![aktuelle_mm_config](https://cloud.githubusercontent.com/assets/2067428/25332473/dd60180c-28e6-11e7-86de-a3b9b4dcc526.JPG)

In einem Metamodel wird das Atribut URL verwendet.
Im Backend funktioniert auch alles beim Eingeben der Datensätze.
Wenn jetzt über das Frontend-Editing die Daten eingegeben werden und das Feld URL leer bleibt, wird der Datensatz nicht gespeichert und folgende Fehlermeldung ausgegeben:

Property homepage (url) did not accept the value (The values differ. Encountered type array expected string (Found array ( 0 => '', 1 => '', ), expected '')).

siehe auch https://community.contao.org/de/showthread.php?65745-Fehlermeldung-beim-Frontend-Editing&p=438470&viewfull=1#post438470

**Comment by zonky2** [comment]
@richardhj can you check this...

**Comment by richardhj** [comment]
… assign me, @zonky2

**Comment by richardhj** [comment]
The `FormTextField` does not support multiple text fields within the widget (`$arrFieldDef['eval']['size'] = 2;`).

Enabling the setting `trim_title` within the attribute's config will help not to end up in the error.

We have to decide to
* either support the input of the href exclusively without title ➡️ this might lead to data loss when `trim_title` is enabled but it cannot be edited in the frontend
* or to support multiple text fields in the `FormTextField` (how?).

**Comment by discordier** [comment]
IMO we will need an own widget for the latter one but it feels like the way we have to go.
Sadly we can not solve this upstream, as Contao 3.5 is feature complete and we would never get this into there then.

**Comment by zonky2** [comment]
fixed in MM 2.2
