### ISSUE TITLE
Error Datum-Attribut beim FE

### ISSUE THREAD

**Issue by Schmidty2** [MetaModels/contao-frontend-editing#11]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

PHP 5.6.30

![aktuelle_mm_config](https://cloud.githubusercontent.com/assets/2067428/25332603/608ca3f8-28e7-11e7-9fc4-90920e939e1f.JPG)

In einem Metamodel wird das Atribut Datum verwendet.
Im Backend funktioniert auch alles beim Eingeben der Datensätze.
Wenn jetzt über das Frontend-Editing die Daten eingegeben werden und im Feld geburtsdatum ein gültiges Datum eingetragen wird, wird der Datensatz nicht gespeichert und folgende Fehlermeldung ausgegeben:

Property geburtsdatum (timestamp) did not accept the value (The values differ. Encountered type integer expected string (Found 182300400, expected '12.10.1975')).

siehe auch https://community.contao.org/de/showthread.php?65745-Fehlermeldung-beim-Frontend-Editing&p=438470&viewfull=1#post438470

**Comment by zonky2** [comment]
@richardhj can you check this...

**Comment by richardhj** [comment]
… assign me, @zonky2

**Comment by richardhj** [comment]
This is the pull at the attribute's repository fixing the error: MetaModels/attribute_timestamp#29

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Schmidty2 could you please have a final look at this and tell if your issue has been resolved?

**Comment by richardhj** [comment]
Well, that was closed quickly…

**Comment by zonky2** [comment]
upps! MiniModel is very fast! "she" should close the ticket after one week... @stefanheimes it´s your girl :D

**Comment by dmolineus** [comment]
> upps! MiniModel is very fast! "she" should close the ticket after one week... @stefanheimes it´s your girl :D

Seems like she's bored ;)

**Comment by zonky2** [comment]
it´s tested
