### ISSUE TITLE
Working attributes in MM 2.2

### ISSUE THREAD

**Issue by zonky2** [MetaModels/contao-frontend-editing#15]
Edit: 06.09.2024

- [x] https://github.com/MetaModels/attribute_alias
- [x] https://github.com/MetaModels/attribute_checkbox
- [x] https://github.com/MetaModels/attribute_color - worked with next version of https://github.com/contao-community-alliance/contao-textfield-multiple-bundle - without colorpicker, you have to implement this yourself
- [x] https://github.com/MetaModels/attribute_combinedvalues
- [x] https://github.com/MetaModels/attribute_country
- [x] https://github.com/MetaModels/attribute_decimal
- [x] https://github.com/MetaModels/attribute_file - from version MM 2.2; included dropzone and delete files
- [x] https://github.com/MetaModels/attribute_langcode
- [x] https://github.com/MetaModels/attribute_longtext - without RTE, you have to implement this yourself; but CSS classes are output
- [x] https://github.com/MetaModels/attribute_numeric
- [x] https://github.com/MetaModels/attribute_rating
- [x] https://github.com/MetaModels/attribute_select - without Popup-Wizard
- [x] https://github.com/MetaModels/attribute_tablemulti - after install https://github.com/contao-community-alliance/contao-multicolumnwizard-frontend-bundle - New version with Vanilla Script for MM 2.2
- [x] https://github.com/MetaModels/attribute_tabletext - after install https://github.com/contao-community-alliance/contao-multicolumnwizard-frontend-bundle - New version with Vanilla Script for MM 2.2
- [x] https://github.com/MetaModels/attribute_tags - without Popup-Wizard and Checkbox-Wizard
- [x] https://github.com/MetaModels/attribute_text
- [x] https://github.com/MetaModels/attribute_timestamp - without datepicker, you have to implement this yourself; but CSS classes are output
- [x] https://github.com/MetaModels/attribute_url - worked with next version of https://github.com/contao-community-alliance/contao-textfield-multiple-bundle - without URL-picker, you have to implement this yourself

**Comment by richardhj** [comment]
Good work!

**Comment by richardhj** [comment]
For the datepicker, colorpicker and rte, we decided to add a css class to the widget in the frontend. Doing so, the frontend developer can implement the picker on himself/herself - either in jQuery, MooTools or VanillaJS. See contao-community-alliance/dc-general-contao-frontend#3

**Comment by richardhj** [comment]
I don't know whats the status of the MutiColumnWizard, but to use the [attribute_tabletext](https://github.com/metamodels/attribute_tabletext) in the frontend, I suggest installing [contao-multicolumnwizard-frontend](https://github.com/richardhj/contao-multicolumnwizard-frontend). I created a FE hack of the MCW a time ago.

**Comment by zonky2** [comment]
if the FE-MCW ready to testing?

**Comment by richardhj** [comment]
@zonky2 you install my extension mentioned above.
We can put my package in the "suggest" sector of the composer.json
But:
What does @stefanheimes say to the MCW in the Frontend? (Stefan, see my comment above).

EDIT:
The reason, why there is no official FE-MCW, is stated [here](https://community.contao.org/de/showthread.php?57338-MultiColumnWizard-im-Frontend&p=371405&viewfull=1#post371405).
However, as the tabletext attribute uses textfield exclusively, my FE-MCW hack is fully suitable.

**Comment by stefanheimes** [comment]
I have try it in the FE it runs. But as said, it use the backend Widgets. I have to take a look into the hack you mention. Maybe we can add it to the main Project of the mcw.

**Comment by zonky2** [comment]
Updated...

**Comment by zonky2** [comment]
Updated...

**Comment by zonky2** [comment]
updated and ready with kown limitation of different picker and wizards
