### ISSUE TITLE
undefinierte Klasse

### ISSUE THREAD

**Issue by Schmidty2** [MetaModels/contao-frontend-editing#2]
Hallo,

ich habe das aktuelle metamodels/bundle_all im Einsatz.
Jetzt habe ich via Composer metamodels/contao-frontend-editing dazu installiert:

![grafik](https://cloud.githubusercontent.com/assets/2067428/21073634/6d7e8abc-bee4-11e6-97ba-e7a01c6a076a.png)

Nach der Installation wird sowohl im Backend als auch im Frontend nur noch eine weisse Seite angezeigt. In der Contao error.log steht mehrfach folgender Eintrag:

PHP Fatal error:  Undefined class constant 'RENDER_ITEM_LIST' in /is/htdocs/wpxxxxx/www/verzeichnisname/system/modules/metamodels-contao-frontend-editing/config/event_listeners.php on line 32

Wenn im Verzeichnis metamodels-contao-frontend-editing eine .skip-Datei angelegt wird, läuft alles wieder wie vorher. Hier noch ein paar technische Angaben:
HostEurope Webserver medium
PHP 5.6.27
Composer läuft (bisher) ohne Fehlermeldungen

**Comment by richardhj** [comment]
Hallo Schmidty2,
die Version `2.0.0-alpha15` von MetaModels ist noch nicht veröffentlicht.
Füge, bis dahin, folgendes in deine `composer.json` ein:
```
  "metamodels/core": "dev-hotfix/alpha-15 as 2.0.0",
```

Gehe dazu bei Composer im Contao-Backend unter Einstellungen, dann Experteneinstellungen und dann die Zeile in den Block `"require": {}`
