### ISSUE TITLE
FEE Eingabemaske: automatische Wertevorgaben

### ISSUE THREAD

**Issue by bastlwastl** [MetaModels/contao-frontend-editing#24]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.1        |                               |
| Contao version:                     |     3.5.27       |                                |
| MetaModels version:                 |      2.0.x.dev      |                                |
| Installation via composer:          |    yes    |                              |
| Installed MetaModels packages:      |     bundle_all 2.0.0      |                                 |
| DCG version:                        |     dc-general 2.0.0-beta40 / dc-general-contao-frontend dev-master      |                                 |

## Issue description

Eingabefelder des FEE lassen sich nicht vorbelegen.?.

` <?php
$GLOBALS['TL_DCA']['<MM-Table-Name>']['fields']['<Field-Column-Name>']['default'] = <Value>; `

Dies funktioniert im BE, jedoch nicht im FE.

**Comment by richardhj** [comment]
On the one hand, I would recommend to create an event listener within system/modules/metamodelsboilerplate/config/event_listeners.php
with the content
```php
<?php

use ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent;

return array
(
    BuildDataDefinitionEvent::NAME => [
        [
            function (BuildDataDefinitionEvent $event) {
                if ($event->getContainer()->getBasicDefinition()->getDataProvider() !== 'mm_employee') {
                    return;
                }

                $property = $event->getContainer()->getPropertiesDefinition()->getProperty('biography');
                $property->setDefaultValue('Test');
            },
            -100,
        ],
    ],
);
```

On the other hand, there is something missing [here](https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/654c6017b59dd3257897aa69c5187f7ac0b74213/src/View/DefaultWidgetBuilder.php#L84)?

```diff
        $varValue = $event->getValue();
+       if (null === $varValue) {
+           $varValue = $property->getDefaultValue();
+       }
```

**Comment by zonky2** [comment]
ich habe das mal mit dem BE verglichen - hier https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php#L399 liefert `$event->getValue()` schon den Defaultwert mit...

könnte im BE hier herkommen https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CreateHandler.php#L77

**Comment by zonky2** [comment]
damit siehts ganz gut aus
https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/master/src/View/ActionHandler/CreateHandler.php#L39-L60

```
    public function process()
    {
        $environment     = $this->getEnvironment();
        $event           = $this->getEvent();
        $definition      = $environment->getDataDefinition();
        $basicDefinition = $definition->getBasicDefinition();

        if (!$basicDefinition->isCreatable()) {
            throw new DcGeneralRuntimeException('DataContainer ' . $definition->getName() . ' is not creatable');
        }
        // We only support flat tables, sorry.
        if (BasicDefinitionInterface::MODE_FLAT !== $basicDefinition->getMode()) {
            return;
        }

        $dataProvider       = $environment->getDataProvider();
        $propertyDefinition = $definition->getPropertiesDefinition();
        $properties         = $propertyDefinition->getProperties();
        $model              = $dataProvider->getEmptyModel();
        $clone              = $dataProvider->getEmptyModel();

        // If some of the fields have a default value, set it.
        foreach ($properties as $property) {
            $propName = $property->getName();

            if ($property->getDefaultValue() !== null) {
                $model->setProperty($propName, $property->getDefaultValue());
                $clone->setProperty($propName, $property->getDefaultValue());
            }
        }

        $editMask = new EditMask($environment, $model, $clone, null, null);

        $event->setResponse($editMask->execute());
    }
```

**Comment by richardhj** [comment]
Hatte nicht im Hinterkopf, dass `defaultValue` nur bei `create` greift.
+1 @zonky2

**Comment by richardhj** [comment]
Closed as contao-community-alliance/dc-general-contao-frontend#8 is merged.
