### ISSUE TITLE
add new/create link to MM template

### ISSUE THREAD

**Issue by zonky2** [MetaModels/contao-frontend-editing#25]
currently you can insert the "New-Button" manually into the output list template - it would be nice if you get access to the URL of the edit page to create a new entry with "act=create" automatically.

**Comment by richardhj** [comment]
What do you mean?
You already have the "save and create" button on the edit page.

**Comment by zonky2** [comment]
we have "save" and "save and new" at edit page... but at list page we don't have that there

How can the user e.g. create the first item if we don't have one yet?

**Comment by richardhj** [comment]
You have to use this template for the list: [ce_metamodel_list_edit](https://github.com/MetaModels/contao-frontend-editing/blob/master/contao/templates/ce_metamodel_list_edit.html5)

**Comment by zonky2** [comment]
Wow! I should add this at manual...

Thx!

**Comment by zonky2** [comment]
http://metamodels.readthedocs.io/de/latest/manual/extended/frontend_editing.html#arbeiten-im-frontend
