### ISSUE TITLE
Eigene FEE-Templates für die (Form) Widgets

### ISSUE THREAD

**Issue by tognit** [MetaModels/contao-frontend-editing#27]
Hallo zusammen

Ist das richtig, dass man für das FEE kein eigenes Template verwenden kann?
Möchte eigentlich die FEE-Formulare selber gestalten (Bootstrap usw.).

So wie z.B. mit Haste

Gruss
Steven

**Comment by zonky2** [comment]
soweit korrekt! es wird die Maske bzw. die Widget vom BE in das FE "gemappt"

es gib aber ein "umschließendes" Template, wo man einige kleine Sachen anpassen kann fängt glaube ich mit dcfe_... an

das ist aber "global" und gilt für alle FEE-Ausgaben... steht auf der Wunschliste, das individuell auswählbar zu machen

**Comment by UB3RL33T** [comment]
Hallo auch von mir,

ich wollte mal Fragen wie denn der Status bei diesem feature ist, wir würden nämlich sehr gerne individuelle Templates für FEE in einem Projekt nutzen.

Leider bin ich mit dem MM-Core nicht vertraut, aber mit ein paar pointern, wie man das Feature umsetzen würde, könnten wir ggf. eine Implementation anfangen und einen PR aufmachen.

Grüße
Tobi

**Comment by zonky2** [comment]
@richardhj @baumannsven könnt ihr was dazu sagen?

**Comment by zonky2** [comment]
man kann per DCA für das FE ein eigenes Template für jedes Widget in die Eingabemaske einschleusen - z. B.

```
if (TL_MODE === 'FE') {
    $GLOBALS['TL_DCA']['mm_associations']['fields']['district_associations']['eval']['customTpl'] = 'form_checkbox_fee_district_associations';
}
```

@baumannsven macht ggf. noch eine Anpassung für die Auswahl des Templates im BE für FE und BE

**Comment by stu2019** [comment]
Hallo

das wäre ein großer Schritt für das FEE

**Comment by zonky2** [comment]
wichtig wäre neben der Anpassung der Attribute bzw. der entsprechenden Form-Widgets die Anpassbarkeit des umschließenden Templates `dcfe_general_edit.html5`

Edit: aktuell nicht möglich - siehe https://github.com/MetaModels/contao-frontend-editing/issues/50

**Comment by zonky2** [comment]
implementiert in MM 2.3 https://metamodels.readthedocs.io/de/latest/manual/new-in-mm-23.html#frontend-editing-fee
