### ISSUE TITLE
Editmask css classes for attributes

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/contao-frontend-editing#28]
Can you provide the css classes field for the attributes for output this classes in the frontend?

**Comment by richardhj** [comment]
Using the "Backend class" for the frontend as well, wdyt?

**Comment by richardhj** [comment]
<img width="497" alt="screen shot 2018-09-04 at 16 22 31" src="https://user-images.githubusercontent.com/1284725/45037204-bda63180-b05e-11e8-866f-e05f7f83807c.png">

**Comment by baumannsven** [comment]
When im style the edit mask in the frontend their i can use this field for styling my widgets.
I think change the description, if frontend editing is installed. So the user see here this classes provides in the FE edit mask too.

**Comment by zonky2** [comment]
write "CSS class" and "Here you can set css class(es)..." :D

**Comment by richardhj** [comment]
See contao-community-alliance/dc-general-contao-frontend#15.

**Comment by zonky2** [comment]
@richardhj can you change the translation keys/texts - see https://github.com/MetaModels/contao-frontend-editing/issues/28#issuecomment-419045231
