### ISSUE TITLE
Alias is not generated when attr alias checkbox "unique value" and "force alias regenerating" is checked 

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/contao-frontend-editing#29]
I´m on the latest mm 2.0 branch via composer with contao 3.5.35

As mentioned in headline, in FEE no alias is generated, when these 2 checkboxes are checked in backend. 

even after jumping from "create" to "edit" mode and saving again.
It works in edit mode - if i chance e.g. the value of the input field responsible for the alias.

Only If i leave "force alias regenerating" unchecked the alias is generated in create mode for  a NEW entry.

**Comment by richardhj** [comment]
You want to implement MetaModels/core#1247 until it is merged (soon!).

**Comment by m-r-h-n** [comment]
that was fast - thanx alot. works :-)
