### ISSUE TITLE
Fatal error in BE after installing MetaModels/contao-frontend-editing

### ISSUE THREAD

**Issue by tsarma** [MetaModels/contao-frontend-editing#3]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6      |                                  |
| Contao version:                     |   3.5.19       |                                  |
| MetaModels version:                 |   2.0.0       |                                  |
| Installation via composer:          | yes  |                                  |
| Installed MetaModels packages:      |  metamodels/core,   metamodels/bundle_all, MetaModels/contao-frontend-editing      |
| DCG version:                        |          |                                  |

After installing `MetaModels/contao-frontend-editing ` backend  is not accessable

````
PHP Fatal error:  Undefined class constant 'RENDER_ITEM_LIST' in /var/www/_Contao/contao3519_MetaModelDemo2/system/modules/metamodels-contao-frontend-editing/config/event_listeners.php on line 30
````

## Screenshots
![screen shot 2016-12-14 at 09 39 44](https://cloud.githubusercontent.com/assets/683894/21175219/8c77983c-c1e1-11e6-9bdf-4d7f0e2208d1.png)

**Comment by richardhj** [comment]
Duplicate of #2 
Install MetaModels@`dev-hotfix/alpha-15`

**Comment by tsarma** [comment]
Ok thank you, with that i was able to install it at least.

But DCA `metamodel_fe_editing` , `metamodel_fe_editing_page` and etc. are not loading!
