### ISSUE TITLE
issue with fee and filtered attribute_tags?

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/contao-frontend-editing#32]
Hi,
I´m on latest MM, latest dc-general-contao-frontend via composer and dc-general 2.0.0-beta48.
I´m not sure if this is the right spot for this issue but obvious to start here…
So my issue:

In FEE i have a metamodel attached via filtered attribute_tags.
If there is only one option to choose i got the error:

> Property myproperty (tags) did not accept the value (The values differ. Encountered type array expected string (Found array ( ), expected 'my-string-whatever')).

If there are at least 2 options to choose from it works well.

The widget-checkbox is parsed like so with 1 option:
`<span><input type="checkbox" name="attibute" id="opt_attibute_0" class="checkbox" value="attibute-value" checked> <label id="lbl_attibute_0" for="opt_attibute_0">attibute-value</label></span>`

With at least 2 options:
`<span><input type="checkbox" name="attibute[]" id="opt_attibute_0" class="checkbox" value="attibute-value-1" checked> <label id="lbl_attibute-value_0" for="opt_attibute-value_0">attibute-value 1</label></span>
<span><input type="checkbox" name="attibute[]" id="opt_attibute_1" class="checkbox" value="attibute-value-2"> <label id="lbl_attibute-value_1" for="opt_attibute-value_1">attibute-value 2</label></span>`

What it should output, if there is only 1 option I guess:
`<span><input type="checkbox" name="attibute[]" id="opt_attibute_0" class="checkbox" value="attibute-value-1" checked> <label id="lbl_attibute-value_0" for="opt_attibute-value_0">attibute-value 1</label></span>`

As the FEE is actually  the same as the backend edit, it works with no error in backend.

I don´t know if this is an issue in combination with filtered tag options or distinction between normal checkbox / checkbox menu.

Hope i wrote that somehow comprehensible.
Thanks for your effort!

**Comment by zonky2** [comment]
pls contact me at email: info@e-spin.de

**Comment by zonky2** [comment]
> In FEE i have a metamodel attached via filtered attribute_tags.

what is "filtered attribute_tags"?

**Comment by m-r-h-n** [comment]
> > In FEE i have a metamodel attached via filtered attribute_tags.
> 
> what is "filtered attribute_tags"?

Gute Frage :-) 
ein Weilchen her…
Wenn ich mich richtig erinnere ging es in dem Fall um ein checkbox-widget für FEE.
MM erwartete da ein Array auch bei nur 1 Option.
Hab mir da mit einem angepassten Checkboxtemplate beholfen.
Und mit "filtered attribute_tags" meinte ich wohl eine vorgefilterte Liste von Tags.

**Comment by zonky2** [comment]
Also das Attribut/Widget funktioniert in MM 2.2 - in der FE-Maske darf man nicht den Typ "Popup-Widget" auswählen... das gibt es im FE nicht. Eine hierarchische Anordnung kann man mit Anpassung des Templates erstellen.

https://easycaptures.com/fs/uploaded/1399/7699218663.png
