### ISSUE TITLE
"Save and Back"-Button in FEE

### ISSUE THREAD

**Issue by UB3RL33T** [MetaModels/contao-frontend-editing#38]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2      |                                  |
| Contao version:                     |     4.9     |                                  |
| MetaModels version:                 |     2.2-dev     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |     2.2-dev     |                                  |

## Issue description

When using Metamodels FEE there does not seem to be a "Save and Back"-button in the frontend. 

## Steps to reproduce

1. Fire up a Metamodel with FEE with the create permission enabled
2. Go to the "Add new"-Mask in the Frontend
3. You'll have a "Save" and a "Save and New" button, but no "Save and Back"

## Describe the behaviour of the application

When you create an item via FEE and use either of the Save buttons you'll either stay on the item you just created or you are redirected to the create a new item page.

If you then want to go back to the list page you either have to use the navigation or press the back button of your browser multiple times because the referer points to the previous create item page

## Describe the expected behaviour of the application

This is issue would be solved if there were a save and back button, like in the backend.

PS: I'm not sure if this is an FEE issue or rather a DCG issue? 
After glancing over the source code it seems like modifications would be necessary in the DCG-Contao-Frontend package

The listener would have to handle the button event: https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/master/src/Listener/HandleSubmitListener.php#L71
And the button would have to be defined in the Editmask: https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/master/src/View/EditMask.php#L316

**Comment by amenk** [comment]
Ping @zonky2

**Comment by zonky2** [comment]
The problem is, the **edit page has no info about who called it up** - in case of doubt "nobody" e.g. if I enter the URL like this or if I come from a bookmark ... the edit page could be called up from different lists => what then?

Which solution should there be? If necessary input field/picker in the CE/Module-edit?

I usually put my own link/button with a fixed URL or Contao's history-back under the edit mask

**Comment by amenk** [comment]
Very good point, while it would be super nice for user experience to have that functionality.

One possible solution would be to add a save-and-back button which does a save + a history.back() afterwards?

**Comment by UB3RL33T** [comment]
In our setup, the edit-pages are child-pages of the list-pages, so the back function would have to call the parent. 

I think a picker is probably a solid solution, you could then point to the list-page, or any other page for that matter, if you deem it appropriate

The issue I see with the link/button is, that you could fill out the form and then press the back button without submitting.

**Comment by zonky2** [comment]
It is now optionally possible to configure own buttons for the input mask (FE)
