### ISSUE TITLE
MM2.2 BE Fehler beim speichern der Einstellungen zu den Eingabefeldern

### ISSUE THREAD

**Issue by Ainschy** [MetaModels/contao-frontend-editing#39]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.4        |                                  |
| Contao version:                     |   4.9.5       |                                  |
| MetaModels version:                 |    2.2      |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |    all 2.2      |                                  |
| DCG version:                        |    dev-release/2.2.0      |                                  |

## Issue description

Eingabemasken lassen sich im BE nicht bearbeiten, beim speichern und anlegen.

## Describe the behaviour of the application

An exception occurred while executing 'UPDATE tl_metamodel_dca SET tl_metamodel_dca.pid = ?, tl_metamodel_dca.sorting = ?, tl_metamodel_dca.tstamp = ?, tl_metamodel_dca.name = ?, tl_metamodel_dca.rendertype = ?, tl_metamodel_dca.ptable = ?, tl_metamodel_dca.rendermode = ?, tl_metamodel_dca.showColumns = ?, tl_metamodel_dca.backendsection = ?, tl_metamodel_dca.backendicon = ?, tl_metamodel_dca.backendcaption = ?, tl_metamodel_dca.panelLayout = ?, tl_metamodel_dca.iseditable = ?, tl_metamodel_dca.iscreatable = ?, tl_metamodel_dca.isdeleteable = ?, tl_metamodel_dca.fe_editButtons = ?, tl_metamodel_dca.fe_overrideEditButtons = ? WHERE id = ?' with params ["6", "0", 1599567574, "BE", "standalone", "", "flat", "", "metamodels", null, "a:2:{i:0;a:3:{s:8:\"langcode\";s:2:\"en\";s:5:\"label\";s:9:\"Resourcen\";s:11:\"description\";s:0:\"\";}i:1;a:3:{s:8:\"langcode\";s:2:\"de\";s:5:\"label\";s:9:\"Resourcen\";s:11:\"description\";s:0:\"\";}}", "filter;sort", "1", "1", "1", "", "", "6"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `contao`.`tl_metamodel_dca`.`fe_overrideEditButtons` at row 1

@baumannsven

**Comment by baumannsven** [comment]
Fixed in da678e1c83068c3847975a2e1b7a059004cef261
