### ISSUE TITLE
Frontend edit link throws fatal error.

### ISSUE THREAD

**Issue by tsarma** [MetaModels/contao-frontend-editing#4]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6      |                                  |
| Contao version:                     |   3.5.19       |                                  |
| MetaModels version:                 |   dev-hotfix/alpha-15       |                                  |
| Installation via composer:          | yes  |                                  |
| Installed MetaModels packages:      |  metamodels/core,   metamodels/bundle_all, 
| MetaModels/contao-frontend-editing      | dev-hotfix/checkbox  |
| DCG version:                        |    dev-hotfix/beta-39      |                                  |

When I click the link "Edit item", results in error  below
````
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_movies is not creatable thrown in composer/vendor/contao-community-alliance/dc-general-contao-frontend/src/View/ActionHandler/EditHandler.php on line 48
````

More details are here in this forum link:
https://community.contao.org/de/showthread.php?64443-Frontend-editing-how-to-create-the-edit-link-and-link-to-member-data

**Comment by discordier** [comment]
First off, before we search for a bug, you did think about making your input screen creatable?
Next, you also did think about selecting it for your member group (or the anonymous group) in the combinations (the icon to the very right)?

**Comment by tsarma** [comment]
No, after checking input screen creatable, the error I have mention is gone away.  
Yes, I've set it to anonymous group.

But now I have new series of errors, and also I think this is not my imagination of frontend editable. I wanted to define only some attributes editable in the frontend not all of them. Any way  I thank you for the guide.

**Comment by discordier** [comment]
Then omit the attributes you do not want to be editable in the input screen.
What is in there, is editable (likewise in the backend).

By combining different attribute collections in different input screens and assigning these to certain member groups you can restrict editing of various attributes to certain member groups.

We are aware that this feature heavily lacks documentation (despite being just beta) but we currently do not have the man power to document it. Maybe you want to jump in and add it to https://github.com/MetaModels/docs

**Comment by tsarma** [comment]
Once again thank you for the valuable tips and your efforts in creating MM. I never had to use this module so far, but I know MM can be a very useful module in some cases. Right now I am learning about MM. May be as you said, I will be in the position to contribute later on.
