### ISSUE TITLE
checkboxes are not saved

### ISSUE THREAD

**Issue by heimseiten** [MetaModels/contao-frontend-editing#41]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |7.4          |                                  |
| Contao version:                     |4.9.13          |                                  |
| MetaModels version:                 |2.2@dev          |                                  |
| Installation via composer:          | no |                                  |
| Installed MetaModels packages:      |all          |                                  |
| DCG version:                        | 2.2@dev         |                                  |

## Issue description

checkboxes are not saved with frontend-editing

## Steps to reproduce

1. setup a metamodel with a checkbox
2. setup frontend-editing
3. try to save a checkbox in the frontend

## Describe the behaviour of the application

every other field gets save except checkboxes

## Describe the expected behaviour of the application

save the state of the checkbox

**Comment by zonky2** [comment]
have you more information with debug mode like error, exception...?

**Comment by heimseiten** [comment]
no, there is no error and you are redirected to the "successfully sent" page

**Comment by zonky2** [comment]
I have the same envronment and save works

https://easycaptures.com/fs/uploaded/1399/0043145562.png

have you own scripts implemented?

**Comment by heimseiten** [comment]
Thank you zonky2. Yes there are scripts, but not related to metamodels. I will do some more tests and let you know.

**Comment by heimseiten** [comment]
Sorry for the issue. It was caused by a JavaScript code. But I don't know why. But now I fixed it.

I use localStorage to store the data of a large form. Because when the internet connection is not stable or the user hit refresh by mistake the data shouldn't be lost.


With this code the checkbox is not saved:

```
<script>
allInputs = document.querySelectorAll('input:not([type="hidden"]), textarea')

    allInputs.forEach(element => { 
        element.value = localStorage.getItem(element.name)
        element.addEventListener("keyup", e => { 
            localStorage.setItem(e.target.name, e.target.value)
        })
    })
</script>
```

When the checkbox not got saved in the localStorage, the checkbox is saved in the metamodel:
```
<script>
allInputs = document.querySelectorAll('input:not([type="hidden"]):not([type="checkbox"]), textarea')

    allInputs.forEach(element => { 
        element.value = localStorage.getItem(element.name)
        element.addEventListener("keyup", e => { 
            localStorage.setItem(e.target.name, e.target.value)
        })
    })
</script>
```

**Comment by zonky2** [comment]
MM can only store what arrives as POST at the server - you should check this
