### ISSUE TITLE
Frontend edit buttons: crashes when a cleartext Name for a button is used

### ISSUE THREAD

**Issue by stu2019** [MetaModels/contao-frontend-editing#44]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.4     |                                  |
| Contao version:                     |     4.9.13     |                                  |
| MetaModels version:                 |     2.2     |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |    FEE      |                                  |
| DCG version:                        |    2.1.9      |                                  |

## Issue description

Frontend edit buttons: try to put the desired Clear-Text Label-Name like"Zurück" into the label field will cause an critical error. The common User expect to be able to put the Buttonname into this field. Not just the name of the translation.

## Steps to reproduce

1. Choose Metamodels -> Eingabemaske. Goto Frontend edit buttons 
2. Define something like: Name= closeNback Label= Zurück .... 
3. Save
4. In FE open an Page with frontend edit buttons -> Contao crashes 

## Describe the behaviour of the application
```
Logfile:  Uncaught PHP Exception TypeError: "substr() expects parameter 3 to be int, bool given" at /html/contao/vendor/metamodels/contao-frontend-editing/src/EventListener/DcGeneral/MetaModel/EditButtons/OverrideEditModelButtons.php line 95 {"exception":"[object] (TypeError(code: 0): substr() expects parameter 3 to be int, bool given at /html/contao/vendor/metamodels/contao-frontend-editing/src/EventListener/DcGeneral/MetaModel/EditButtons/OverrideEditModelButtons.php:95)"} []
```

## Describe the expected behaviour of the application
Show the button with the label Zurück

## Screenshots

<img width="1634" alt="Bildschirmfoto 2021-05-19 um 16 05 11" src="https://user-images.githubusercontent.com/49641522/118826754-0ad49b00-b8bc-11eb-8430-0f42d053308f.png">

**Comment by zonky2** [comment]
Fixed in MM 2.2
