### ISSUE TITLE
FEE: Close without save a page with mandatory field ask to fill this fields before closing

### ISSUE THREAD

**Issue by stu2019** [MetaModels/contao-frontend-editing#45]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.4      |                                  |
| Contao version:                     |      4.9.13    |                                  |
| MetaModels version:                 |     2.2     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |     all     |                                  |
| DCG version:                        |      2.1.9    |                                  |

## Issue description

FEE: Close without save a page with mandatory field ask to fill this fields before closing

## Steps to reproduce

1. Create a Metamodel with some Attributes.
2. In Eingabemasken define some Fields to mandatory
3. Define a Frontendbutton closeNback (see Screenshot) with Not save
4. Create a new record, don't fill the mandatory fields
5. click on closeNback / Abbrechen -> instead of close the page and go to the Forward page, as expected, the user will be forced to fill the mandatory fields.

## Describe the behaviour of the application
 Instead of close the page and go to the Forward page, as expected, the user will be forced to fill the mandatory fields.

## Describe the expected behaviour of the application
Close the page immediately and go to the forward page

## Screenshots
<img width="745" alt="Bildschirmfoto 2021-05-19 um 16 16 41" src="https://user-images.githubusercontent.com/49641522/118828608-b3372f00-b8bd-11eb-8e8e-b004143f735c.png">
<img width="1634" alt="Bildschirmfoto 2021-05-19 um 16 16 03" src="https://user-images.githubusercontent.com/49641522/118828515-a0245f00-b8bd-11eb-851a-f135b8b9e380.png">

**Comment by zonky2** [comment]
workaround - add `novalidate` at dcfe_general_edit.html5

**Comment by zonky2** [comment]
we add css class `nosave` at buttons - https://github.com/contao-community-alliance/dc-general-contao-frontend/pull/34

we disable the HTML5-check automaticaly in MM 2.2

**Comment by zonky2** [comment]
fixed in MM 2.2
