### ISSUE TITLE
No front-end editing on nightly package

### ISSUE THREAD

**Issue by joejemmely** [MetaModels/contao-frontend-editing#5]
Hello,

I'm very interested in trying the new front-end editing feature however it seems that it's not yet part of the nightly build from the project website. Unfortunately I can't managed to install via composer either but this is an issue with my test environnement and not related to the module.

Is there any other way I can test it ?

**Comment by discordier** [comment]
No, sorry.
The nightlies are snapshots of tagged releases (alpha, beta, rc and stable) which should be somewhat stable but are still not recommended use.
The frontend editing however is neither bundled in bundle-all nor in the nightly builds.
The use case is so narrow that we do not feel it should be pushed on all installing MetaModels (you usually should only install what you need).

I therefore suggest fixing your test environment or setup a test environment locally and push the result to the server then.

**Comment by tsarma** [comment]
I am also trying MetaModels FEE-> If you want to test you look here http://tinyurl.com/zr869x3 . 
Or download whole installation here http://tinyurl.com/z49t5hl .

**Comment by zonky2** [comment]
o.k. - looks good... have you the login data to the demo if we can work with FEE?

**Comment by tsarma** [comment]
Backend 
k.jones | kevinmmfee

**Comment by zonky2** [comment]
hmm... I mean Login as member user e.g.
johndoe | johndoejohndoe

**Comment by zonky2** [comment]
@joejemmely ply use composer and install the FEE package
