### ISSUE TITLE
Alias attribute not working in FEE

### ISSUE THREAD

**Issue by tsarma** [MetaModels/contao-frontend-editing#6]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:
| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6      |                                  |
| Contao version:                     |   3.5.19       |                                  |
| MetaModels version:                 |   dev-hotfix/alpha-15       |                                  |
| Installation via composer:          | yes  |                                  |
| Installed MetaModels packages:      |  metamodels/core,   metamodels/bundle_all, 
| MetaModels/contao-frontend-editing      | dev-hotfix/checkbox  |
| DCG version:                        |    dev-hotfix/beta-39      |                                  |

## Issue description
Attribute alias is working only in backend. 

![alias](https://cloud.githubusercontent.com/assets/683894/21429984/767f30ae-c861-11e6-8c2b-aa77f22ef4b0.jpg)

In FEE alias attribute is not generated.

**Comment by richardhj** [comment]
The reason might that the alias attribute is not in the FEE input mask. The alias generation will not be triggered because the alias attribute does not pass the `isAttributeSet()`.
For my purposes, I could quickfix it with this:
```php

/**
 * Class FrontendEditingItem
 * @package MetaModels
 */
class FrontendEditingItem extends Item
{

	/**
	 * Override this function as we want to make sure that all attributes get notified by saving the item.
	 * 
	 * @param string $strAttributeName
	 *
	 * @return true
	 */
	public function isAttributeSet($strAttributeName)
	{
		return true;
	}
}
```

**Comment by discordier** [comment]
I guess we must rewrite the save handler of the alias attribute to handle the model pre persist event of dc-general. This should solve the problems then.

**Comment by zonky2** [comment]
same question to generate alias without inside input mask: https://github.com/MetaModels/attribute_alias/issues/21

**Comment by richardhj** [comment]
The alias attributes works as it is supposed to be. The alias generation within the `modelSaved()` method will be triggered by the dc-general-frontend as well.
The alias generation works even if the alias field is not part of the FE input mask (@zonky2).

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tsarma could you please have a final look at this and tell if your issue has been resolved?
