### ISSUE TITLE
Buttons im Frontend-Edit - Parameter und "Nicht speichern"

### ISSUE THREAD

**Issue by tognit** [MetaModels/contao-frontend-editing#60]
Wenn man bei einem Frontend Button "Nicht speichern" anwählt, werden die Tokens im Feld "Parameter" nicht berücksichtigt.

MM dev-feature/2.3.0

In der NotSaveEditModelButton.php werden die SimpleTokens nicht verarbeitet und in der ForwardSaveEditModelButton.php schon.

![buttons](https://github.com/MetaModels/contao-frontend-editing/assets/1794459/17b51817-f614-4a48-9b0a-e6f74343d339)

**Comment by zonky2** [comment]
Welche MM-Version?

Kannst Du das etwas mehr ausführen, damit ich das nachstellen kann? So verstehe ich das noch nicht ganz :(

Edit: hmm... muss ich mal testen

**Comment by cliffparnitzky** [comment]
Ja, kann ich bestätigen.

**Comment by zonky2** [comment]
ich auch :D

ist an der Stelle etwas tricky um an die Daten zu kommen - bin am Ball...

**Comment by cliffparnitzky** [comment]
> ist an der Stelle etwas tricky um an die Daten zu kommen

Jepp. So sehe ich das auch.

**Comment by zonky2** [comment]
Eventlistener `NotSaveEditModelButton` angepasst - sollte damit gefixt sein ... Update sollte in ca. 5 Minuten abrufbar sein

**Comment by cliffparnitzky** [comment]
Bestätigt ... funktioniert. Danke @zonky2

Just to mention: ist ab Version 2.3 verfügbar.

**Comment by tognit** [comment]
Super Sache!!! Besten Dank! Funktioniert tiptop!
