### ISSUE TITLE
Buttons im Frontend-Edit - Parameter (Insert-Tags)

### ISSUE THREAD

**Issue by tognit** [MetaModels/contao-frontend-editing#61]
Könnte man als Parameter auch Insert-Tags verwenden? Somit könnte man z.B. mit einem eigenen Insert-Tags auf GET Parameter in der URL zugreifen und z.B. zum Elternelement zurück kehren.

**Comment by zonky2** [comment]
müsste man die beiden Event-Listener anpassen
https://github.com/MetaModels/contao-frontend-editing/tree/master/src/EventListener/DcGeneral/MetaModel/EditButtons/Action

**Comment by zonky2** [comment]
implemented MM 2.3 - thanks @tognit for PR
