### ISSUE TITLE
Need a filePicker

### ISSUE THREAD

**Issue by richardhj** [MetaModels/contao-frontend-editing#8]
When the DCG-Frontend loads the file widget, he is looking for the `$GLOBALS['TL_FFL']['filePicker']`.

The problem: There is no file picker for the front end per default - and there is no general widget 	to come into consideration. For example there is the avatar widget (1 image for upload, preview of the uploaded image) or there is the FineUploader (multiple files for upload).

We need a point in the MetaModels attribute or input mask configuration where the user can decide which widget he wants in the front end.
Different widgets should be able to be implemented.
At this point, `$property->getWidgetType()` must not be `filePicker` https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/a271b53c899c3f55e9c2c31a9c89c623bda2b9d2/src/View/DefaultWidgetBuilder.php#L137-L139

**Comment by discordier** [comment]
this is true, we are lacking many widgets in the frontend so far.
This affects all wizards and pickers so far.

**Comment by Schmidty2** [comment]
+1

**Comment by zonky2** [comment]
@baumannsven 

With the new file uploader, the uploaded files can also be deleted again or decoupled (deselected) from the data set. If necessary, it would be possible to expand the widget via an option so that all files of the target folder are available for selection.

**Comment by zonky2** [comment]
MM 2.2: We have a FEE upload widget that can also preview files and delete them.
